tags = [
    "script", "style", "link", "meta", "li", "desc", "title", "svg", "path", "dialog", "select", "head", "header",
    "foot", "footer", "ul", "nav", "button", "form", "input", "picture", "time", "h2", "h3", "h4", "i", "aside",
    "FreeStarVideoAdContainer", "freestar-video-parent", "reestar-video-child"
]

classes = [
    "progress-bar", "js-menu", "social-share", "post-info__readtime", "cta__description", "cta__inner", "cta__content",
    "hide-mobile", "js-toc", "author-card", "related-posts"
]
