[github]
# GitHub Username
username = "Cubik65536"
# GitHub Token
token = "token"

[upstream_repo]
# Upstream Repository Owner
owner = "owner"
# Upstream Repository Name
repo = "repo"

[contributor_repo]
# Contributor Repository Owner, by default it's the same as the GitHub Username
# owner = "owner"
# Contributor Repository Name, by default it's the same as the Upstream Repository Name
# repo = "repo"
